#if !defined(__IZANAGI_POSTEFFECT_DEFS_H__)
#define __IZANAGI_POSTEFFECT_DEFS_H__

#include "izD3DDefs.h"
#include "izStd.h"
#include "graph/GraphDefs.h"

namespace izanagi {
	/**
	* ポストエフェクトパラメータのクラス
	*/
	enum E_POSTEFFECT_PARAMETER_CLASS {
		E_POSTEFFECT_PARAMETER_CLASS_UNKNOWN = 0,	// その他
		E_POSTEFFECT_PARAMETER_CLASS_SCALAR,		// スカラー
		E_POSTEFFECT_PARAMETER_CLASS_VECTOR,		// ベクトル
		E_POSTEFFECT_PARAMETER_CLASS_MATRIX,		// マトリクス
		E_POSTEFFECT_PARAMETER_CLASS_STRUCT,		// 構造体
		E_POSTEFFECT_PARAMETER_CLASS_ARRAY,			// 配列
		E_POSTEFFECT_PARAMETER_CLASS_SAMPLER,		// サンプラ
		E_POSTEFFECT_PARAMETER_CLASS_OBJECT,		// テクスチャ、シェーダ、または文字列
		
		E_POSTEFFECT_PARAMETER_CLASS_NUM,			// パラメータのクラス数の定義

		E_POSTEFFECT_PARAMETER_CLASS_FORCE_INT32 = 0x7fffffff,	// enum のサイズを IZ_INT と同じにするため
	};

	/**
	* ポストエフェクトパラメータのタイプ
	*/
	enum E_POSTEFFECT_PARAMETER_TYPE {
		E_POSTEFFECT_PARAMETER_TYPE_HALF = 0,		// half
		E_POSTEFFECT_PARAMETER_TYPE_HALF1,			// half1
		E_POSTEFFECT_PARAMETER_TYPE_HALF2,			// half2
		E_POSTEFFECT_PARAMETER_TYPE_HALF3,			// half3
		E_POSTEFFECT_PARAMETER_TYPE_HALF4,			// half4

		E_POSTEFFECT_PARAMETER_TYPE_HALF1x1,		// half1x1
		E_POSTEFFECT_PARAMETER_TYPE_HALF1x2,		// half1x2
		E_POSTEFFECT_PARAMETER_TYPE_HALF1x3,		// half1x3
		E_POSTEFFECT_PARAMETER_TYPE_HALF1x4,		// half1x4

		E_POSTEFFECT_PARAMETER_TYPE_HALF2x1,		// half2x1
		E_POSTEFFECT_PARAMETER_TYPE_HALF2x2,		// half2x2
		E_POSTEFFECT_PARAMETER_TYPE_HALF2x3,		// half2x3
		E_POSTEFFECT_PARAMETER_TYPE_HALF2x4,		// half2x4

		E_POSTEFFECT_PARAMETER_TYPE_HALF3x1,		// half3x1
		E_POSTEFFECT_PARAMETER_TYPE_HALF3x2,		// half3x2
		E_POSTEFFECT_PARAMETER_TYPE_HALF3x3,		// half3x3
		E_POSTEFFECT_PARAMETER_TYPE_HALF3x4,		// half3x4

		E_POSTEFFECT_PARAMETER_TYPE_HALF4x1,		// half4x1
		E_POSTEFFECT_PARAMETER_TYPE_HALF4x2,		// half4x2
		E_POSTEFFECT_PARAMETER_TYPE_HALF4x3,		// half4x3
		E_POSTEFFECT_PARAMETER_TYPE_HALF4x4,		// half4x4

		E_POSTEFFECT_PARAMETER_TYPE_FLOAT,			// float
		E_POSTEFFECT_PARAMETER_TYPE_FLOAT1,			// float1
		E_POSTEFFECT_PARAMETER_TYPE_FLOAT2,			// float2
		E_POSTEFFECT_PARAMETER_TYPE_FLOAT3,			// float3
		E_POSTEFFECT_PARAMETER_TYPE_FLOAT4,			// float4

		E_POSTEFFECT_PARAMETER_TYPE_FLOAT1x1,		// float1x1
		E_POSTEFFECT_PARAMETER_TYPE_FLOAT1x2,		// float1x2
		E_POSTEFFECT_PARAMETER_TYPE_FLOAT1x3,		// float1x3
		E_POSTEFFECT_PARAMETER_TYPE_FLOAT1x4,		// float1x4

		E_POSTEFFECT_PARAMETER_TYPE_FLOAT2x1,		// float2x1
		E_POSTEFFECT_PARAMETER_TYPE_FLOAT2x2,		// float2x2
		E_POSTEFFECT_PARAMETER_TYPE_FLOAT2x3,		// float2x3
		E_POSTEFFECT_PARAMETER_TYPE_FLOAT2x4,		// float2x4

		E_POSTEFFECT_PARAMETER_TYPE_FLOAT3x1,		// float3x1
		E_POSTEFFECT_PARAMETER_TYPE_FLOAT3x2,		// float3x2
		E_POSTEFFECT_PARAMETER_TYPE_FLOAT3x3,		// float3x3
		E_POSTEFFECT_PARAMETER_TYPE_FLOAT3x4,		// float3x4

		E_POSTEFFECT_PARAMETER_TYPE_FLOAT4x1,		// float4x1
		E_POSTEFFECT_PARAMETER_TYPE_FLOAT4x2,		// float4x2
		E_POSTEFFECT_PARAMETER_TYPE_FLOAT4x3,		// float4x3
		E_POSTEFFECT_PARAMETER_TYPE_FLOAT4x4,		// float4x4

		E_POSTEFFECT_PARAMETER_TYPE_INT,			// int
		E_POSTEFFECT_PARAMETER_TYPE_INT1,			// int1
		E_POSTEFFECT_PARAMETER_TYPE_INT2,			// int2
		E_POSTEFFECT_PARAMETER_TYPE_INT3,			// int3
		E_POSTEFFECT_PARAMETER_TYPE_INT4,			// int4

		E_POSTEFFECT_PARAMETER_TYPE_INT1x1,			// int1x1
		E_POSTEFFECT_PARAMETER_TYPE_INT1x2,			// int1x2
		E_POSTEFFECT_PARAMETER_TYPE_INT1x3,			// int1x3
		E_POSTEFFECT_PARAMETER_TYPE_INT1x4,			// int1x4

		E_POSTEFFECT_PARAMETER_TYPE_INT2x1,			// int2x1
		E_POSTEFFECT_PARAMETER_TYPE_INT2x2,			// int2x2
		E_POSTEFFECT_PARAMETER_TYPE_INT2x3,			// int2x3
		E_POSTEFFECT_PARAMETER_TYPE_INT2x4,			// int2x4

		E_POSTEFFECT_PARAMETER_TYPE_INT3x1,			// int3x1
		E_POSTEFFECT_PARAMETER_TYPE_INT3x2,			// int3x2
		E_POSTEFFECT_PARAMETER_TYPE_INT3x3,			// int3x3
		E_POSTEFFECT_PARAMETER_TYPE_INT3x4,			// int3x4

		E_POSTEFFECT_PARAMETER_TYPE_INT4x1,			// int4x1
		E_POSTEFFECT_PARAMETER_TYPE_INT4x2,			// int4x2
		E_POSTEFFECT_PARAMETER_TYPE_INT4x3,			// int4x3
		E_POSTEFFECT_PARAMETER_TYPE_INT4x4,			// int4x4

		E_POSTEFFECT_PARAMETER_TYPE_BOOL,			// bool
		E_POSTEFFECT_PARAMETER_TYPE_BOOL1,			// bool1
		E_POSTEFFECT_PARAMETER_TYPE_BOOL2,			// bool2
		E_POSTEFFECT_PARAMETER_TYPE_BOOL3,			// bool3
		E_POSTEFFECT_PARAMETER_TYPE_BOOL4,			// bool4

		E_POSTEFFECT_PARAMETER_TYPE_BOOL1x1,		// bool1x1
		E_POSTEFFECT_PARAMETER_TYPE_BOOL1x2,		// bool1x2
		E_POSTEFFECT_PARAMETER_TYPE_BOOL1x3,		// bool1x3
		E_POSTEFFECT_PARAMETER_TYPE_BOOL1x4,		// bool1x4

		E_POSTEFFECT_PARAMETER_TYPE_BOOL2x1,		// bool2x1
		E_POSTEFFECT_PARAMETER_TYPE_BOOL2x2,		// bool2x2
		E_POSTEFFECT_PARAMETER_TYPE_BOOL2x3,		// bool2x3
		E_POSTEFFECT_PARAMETER_TYPE_BOOL2x4,		// bool2x4

		E_POSTEFFECT_PARAMETER_TYPE_BOOL3x1,		// bool3x1
		E_POSTEFFECT_PARAMETER_TYPE_BOOL3x2,		// bool3x2
		E_POSTEFFECT_PARAMETER_TYPE_BOOL3x3,		// bool3x3
		E_POSTEFFECT_PARAMETER_TYPE_BOOL3x4,		// bool3x4

		E_POSTEFFECT_PARAMETER_TYPE_BOOL4x1,		// bool4x1
		E_POSTEFFECT_PARAMETER_TYPE_BOOL4x2,		// bool4x2
		E_POSTEFFECT_PARAMETER_TYPE_BOOL4x3,		// bool4x3
		E_POSTEFFECT_PARAMETER_TYPE_BOOL4x4,		// bool4x4

		E_POSTEFFECT_PARAMETER_TYPE_STRING,			// 文字列
		E_POSTEFFECT_PARAMETER_TYPE_TEXTURE,		// テクスチャ

		E_POSTEFFECT_PARAMETER_TYPE_SAMPLER1D,		// 1Dサンプラ
		E_POSTEFFECT_PARAMETER_TYPE_SAMPLER2D,		// 2Dサンプラ
		E_POSTEFFECT_PARAMETER_TYPE_SAMPLER3D,		// 3Dサンプラ
		E_POSTEFFECT_PARAMETER_TYPE_SAMPLERRECT,	// RECTサンプラ
		E_POSTEFFECT_PARAMETER_TYPE_SAMPLERCUBE,	// CUBEサンプラ

		E_POSTEFFECT_PARAMETER_TYPE_NUM,			// パラメータのタイプ数の定義

		E_POSTEFFECT_PARAMETER_TYPE_FORCE_INT32 = 0x7fffffff,	// enum のサイズを IZ_INT と同じにするため
	};

	/**
	* テクスチャタイプ
	*/
	enum E_POSTEFFECT_TEXTURE_TYPE {
		E_POSTEFFECT_TEXTURE_TYPE_NONE = 0,		// NONE,

		E_POSTEFFECT_TEXTURE_TYPE_INPUT_SCENE,	// INPUT_SCENE
		E_POSTEFFECT_TEXTURE_TYPE_INPUT_DEPTH,	// INPUT_DEPTH

		E_POSTEFFECT_TEXTURE_TYPE_PRIVATE,		// PRIVATE
		E_POSTEFFECT_TEXTURE_TYPE_INPUT,		// INPUT

		E_POSTEFFECT_TEXTURE_TYPE_NUM,			// パラメータのタイプ数の定義

		E_POSTEFFECT_TEXTURE_TYPE_FORCE_INT32 = 0x7fffffff,	// enum のサイズを IZ_INT と同じにするため.
	};

	// 頂点シェーダタイプ
	enum E_POSTEFFECT_VTX_SHADER {
		E_POSTEFFECT_VTX_SHADER_SAMPLING_1 = 0,	// １点をサンプリング（デフォルト）
		E_POSTEFFECT_VTX_SHADER_SAMPLING_4,		// 周囲４点をサンプリング
		E_POSTEFFECT_VTX_SHADER_SAMPLING_8,		// 周囲８点をサンプリング
		E_POSTEFFECT_VTX_SHADER_SAMPLING_16,	// 周囲１６点をサンプリング
		E_POSTEFFECT_VTX_SHADER_SAMPLING_5,		// 周囲５点をサンプリング
		E_POSTEFFECT_VTX_SHADER_SAMPLING_7,		// 周囲７点をサンプリング
		E_POSTEFFECT_VTX_SHADER_SAMPLING_9,		// 周囲９点をサンプリング
		E_POSTEFFECT_VTX_SHADER_SAMPLING_13,	// 周囲１３点をサンプリング

		E_POSTEFFECT_VTX_SHADER_NUM,

		E_POSTEFFECT_VTX_SHADER_FORCE_INT32 = 0x7fffffff,
	};

	typedef IZ_UINT	IZ_POSTEFFECT_HANDLE;
	enum {
		IZ_POSTEFFECT_HANDLE_INVALID = 0x7fffffff,
	};
}	// namespace

#endif	// #if !defined(__IZANAGI_POSTEFFECT_DEFS_H__)
