# Builds all the projects in the solution...
.PHONY: all_projects
all_projects: Debug_GLUT 

.PHONY: Debug_GLUT
Debug_GLUT: State_Debug_GLUT Model_Debug_GLUT Motion_Debug_GLUT Material_Debug_GLUT MouseHit_Debug_GLUT Decal_Debug_GLUT MotionInterp_Debug_GLUT MotionBlend_Debug_GLUT MotionBind_Debug_GLUT Shader_Debug_GLUT DebugMesh_Debug_GLUT ProjectedTextureShadow_Debug_GLUT CubeMap_Debug_GLUT Render2D_Debug_GLUT PostEffect_Debug_GLUT Instancing_Debug_GLUT WaterDrop_Debug_GLUT ScreenShot_Debug_GLUT FontBitmap_Debug_GLUT FontFreeType_Debug_GLUT TextParagraph_Debug_GLUT FontRenderer_Debug_GLUT GamePad_Debug_GLUT Binding_Debug_GLUT Event_Debug_GLUT Profiler_Debug_GLUT ObjectReference_Debug_GLUT JobQueue_Debug_GLUT MesssageQueue_Debug_GLUT Parallel_Debug_GLUT Task_Debug_GLUT ResourceManager_Debug_GLUT Archive_Debug_GLUT SampleKit_Debug_GLUT 

# Builds project 'State'...
.PHONY: State_Debug_GLUT
State_Debug_GLUT: SampleKit 
	make --directory="." --file=State.makefile Debug_GLUT

# Builds project 'Model'...
.PHONY: Model_Debug_GLUT
Model_Debug_GLUT: SampleKit 
	make --directory="." --file=Model.makefile Debug_GLUT

# Builds project 'Motion'...
.PHONY: Motion_Debug_GLUT
Motion_Debug_GLUT: SampleKit 
	make --directory="." --file=Motion.makefile Debug_GLUT

# Builds project 'Material'...
.PHONY: Material_Debug_GLUT
Material_Debug_GLUT: SampleKit 
	make --directory="." --file=Material.makefile Debug_GLUT

# Builds project 'MouseHit'...
.PHONY: MouseHit_Debug_GLUT
MouseHit_Debug_GLUT: SampleKit 
	make --directory="." --file=MouseHit.makefile Debug_GLUT

# Builds project 'Decal'...
.PHONY: Decal_Debug_GLUT
Decal_Debug_GLUT: SampleKit 
	make --directory="." --file=Decal.makefile Debug_GLUT

# Builds project 'MotionInterp'...
.PHONY: MotionInterp_Debug_GLUT
MotionInterp_Debug_GLUT: SampleKit 
	make --directory="." --file=MotionInterp.makefile Debug_GLUT

# Builds project 'MotionBlend'...
.PHONY: MotionBlend_Debug_GLUT
MotionBlend_Debug_GLUT: SampleKit 
	make --directory="." --file=MotionBlend.makefile Debug_GLUT

# Builds project 'MotionBind'...
.PHONY: MotionBind_Debug_GLUT
MotionBind_Debug_GLUT: SampleKit 
	make --directory="." --file=MotionBind.makefile Debug_GLUT

# Builds project 'Shader'...
.PHONY: Shader_Debug_GLUT
Shader_Debug_GLUT: SampleKit 
	make --directory="." --file=Shader.makefile Debug_GLUT

# Builds project 'DebugMesh'...
.PHONY: DebugMesh_Debug_GLUT
DebugMesh_Debug_GLUT: SampleKit 
	make --directory="." --file=DebugMesh.makefile Debug_GLUT

# Builds project 'ProjectedTextureShadow'...
.PHONY: ProjectedTextureShadow_Debug_GLUT
ProjectedTextureShadow_Debug_GLUT: SampleKit 
	make --directory="." --file=ProjectedTextureShadow.makefile Debug_GLUT

# Builds project 'CubeMap'...
.PHONY: CubeMap_Debug_GLUT
CubeMap_Debug_GLUT: SampleKit 
	make --directory="." --file=CubeMap.makefile Debug_GLUT

# Builds project 'Render2D'...
.PHONY: Render2D_Debug_GLUT
Render2D_Debug_GLUT: SampleKit 
	make --directory="." --file=Render2D.makefile Debug_GLUT

# Builds project 'PostEffect'...
.PHONY: PostEffect_Debug_GLUT
PostEffect_Debug_GLUT: SampleKit 
	make --directory="." --file=PostEffect.makefile Debug_GLUT

# Builds project 'Instancing'...
.PHONY: Instancing_Debug_GLUT
Instancing_Debug_GLUT: SampleKit 
	make --directory="." --file=Instancing.makefile Debug_GLUT

# Builds project 'WaterDrop'...
.PHONY: WaterDrop_Debug_GLUT
WaterDrop_Debug_GLUT: SampleKit 
	make --directory="." --file=WaterDrop.makefile Debug_GLUT

# Builds project 'ScreenShot'...
.PHONY: ScreenShot_Debug_GLUT
ScreenShot_Debug_GLUT: SampleKit 
	make --directory="." --file=ScreenShot.makefile Debug_GLUT

# Builds project 'FontBitmap'...
.PHONY: FontBitmap_Debug_GLUT
FontBitmap_Debug_GLUT: SampleKit 
	make --directory="." --file=FontBitmap.makefile Debug_GLUT

# Builds project 'FontFreeType'...
.PHONY: FontFreeType_Debug_GLUT
FontFreeType_Debug_GLUT: SampleKit 
	make --directory="." --file=FontFreeType.makefile Debug_GLUT

# Builds project 'TextParagraph'...
.PHONY: TextParagraph_Debug_GLUT
TextParagraph_Debug_GLUT: SampleKit 
	make --directory="." --file=TextParagraph.makefile Debug_GLUT

# Builds project 'FontRenderer'...
.PHONY: FontRenderer_Debug_GLUT
FontRenderer_Debug_GLUT: SampleKit 
	make --directory="." --file=FontRenderer.makefile Debug_GLUT

# Builds project 'GamePad'...
.PHONY: GamePad_Debug_GLUT
GamePad_Debug_GLUT: SampleKit 
	make --directory="." --file=GamePad.makefile Debug_GLUT

# Builds project 'Binding'...
.PHONY: Binding_Debug_GLUT
Binding_Debug_GLUT: SampleKit 
	make --directory="." --file=Binding.makefile Debug_GLUT

# Builds project 'Event'...
.PHONY: Event_Debug_GLUT
Event_Debug_GLUT: SampleKit 
	make --directory="." --file=Event.makefile Debug_GLUT

# Builds project 'Profiler'...
.PHONY: Profiler_Debug_GLUT
Profiler_Debug_GLUT: SampleKit 
	make --directory="." --file=Profiler.makefile Debug_GLUT

# Builds project 'ObjectReference'...
.PHONY: ObjectReference_Debug_GLUT
ObjectReference_Debug_GLUT: SampleKit 
	make --directory="." --file=ObjectReference.makefile Debug_GLUT

# Builds project 'JobQueue'...
.PHONY: JobQueue_Debug_GLUT
JobQueue_Debug_GLUT: SampleKit 
	make --directory="." --file=JobQueue.makefile Debug_GLUT

# Builds project 'MesssageQueue'...
.PHONY: MesssageQueue_Debug_GLUT
MesssageQueue_Debug_GLUT: SampleKit 
	make --directory="." --file=MesssageQueue.makefile Debug_GLUT

# Builds project 'Parallel'...
.PHONY: Parallel_Debug_GLUT
Parallel_Debug_GLUT: SampleKit 
	make --directory="." --file=Parallel.makefile Debug_GLUT

# Builds project 'Task'...
.PHONY: Task_Debug_GLUT
Task_Debug_GLUT: SampleKit 
	make --directory="." --file=Task.makefile Debug_GLUT

# Builds project 'ResourceManager'...
.PHONY: ResourceManager_Debug_GLUT
ResourceManager_Debug_GLUT: 
	make --directory="." --file=ResourceManager.makefile Debug_GLUT

# Builds project 'Archive'...
.PHONY: Archive_Debug_GLUT
Archive_Debug_GLUT: SampleKit 
	make --directory="." --file=Archive.makefile Debug_GLUT

# Builds project 'SampleKit'...
.PHONY: SampleKit_Debug_GLUT
SampleKit_Debug_GLUT: 
	make --directory="." --file=SampleKit.makefile Debug_GLUT

# Cleans all projects...
.PHONY: clean
clean:
	make --directory="." --file=State.makefile clean
	make --directory="." --file=Model.makefile clean
	make --directory="." --file=Motion.makefile clean
	make --directory="." --file=Material.makefile clean
	make --directory="." --file=MouseHit.makefile clean
	make --directory="." --file=Decal.makefile clean
	make --directory="." --file=MotionInterp.makefile clean
	make --directory="." --file=MotionBlend.makefile clean
	make --directory="." --file=MotionBind.makefile clean
	make --directory="." --file=Shader.makefile clean
	make --directory="." --file=DebugMesh.makefile clean
	make --directory="." --file=ProjectedTextureShadow.makefile clean
	make --directory="." --file=CubeMap.makefile clean
	make --directory="." --file=Render2D.makefile clean
	make --directory="." --file=PostEffect.makefile clean
	make --directory="." --file=Instancing.makefile clean
	make --directory="." --file=WaterDrop.makefile clean
	make --directory="." --file=ScreenShot.makefile clean
	make --directory="." --file=FontBitmap.makefile clean
	make --directory="." --file=FontFreeType.makefile clean
	make --directory="." --file=TextParagraph.makefile clean
	make --directory="." --file=FontRenderer.makefile clean
	make --directory="." --file=GamePad.makefile clean
	make --directory="." --file=Binding.makefile clean
	make --directory="." --file=Event.makefile clean
	make --directory="." --file=Profiler.makefile clean
	make --directory="." --file=ObjectReference.makefile clean
	make --directory="." --file=JobQueue.makefile clean
	make --directory="." --file=MesssageQueue.makefile clean
	make --directory="." --file=Parallel.makefile clean
	make --directory="." --file=Task.makefile clean
	make --directory="." --file=ResourceManager.makefile clean
	make --directory="." --file=Archive.makefile clean
	make --directory="." --file=SampleKit.makefile clean

