// NOTE
// type,row,column,is_int,is_float

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF,  1, 1, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF1, 1, 1, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF2, 1, 2, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF3, 1, 3, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF4, 1, 4, IZ_FALSE, IZ_TRUE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF1x1, 1, 1, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF1x2, 1, 2, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF1x3, 1, 3, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF1x4, 1, 4, IZ_FALSE, IZ_TRUE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF2x1, 2, 1, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF2x2, 2, 2, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF2x3, 2, 3, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF2x4, 2, 4, IZ_FALSE, IZ_TRUE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF3x1, 3, 1, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF3x2, 3, 2, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF3x3, 3, 3, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF3x4, 3, 4, IZ_FALSE, IZ_TRUE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF4x1, 4, 1, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF4x2, 4, 2, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF4x3, 4, 3, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_HALF4x4, 4, 4, IZ_FALSE, IZ_TRUE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT,  1, 1, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT1, 1, 1, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT2, 1, 2, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT3, 1, 3, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT4, 1, 4, IZ_FALSE, IZ_TRUE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT1x1, 1, 1, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT1x2, 1, 2, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT1x3, 1, 3, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT1x4, 1, 4, IZ_FALSE, IZ_TRUE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT2x1, 2, 1, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT2x2, 2, 2, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT2x3, 2, 3, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT2x4, 2, 4, IZ_FALSE, IZ_TRUE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT3x1, 3, 1, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT3x2, 3, 2, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT3x3, 3, 3, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT3x4, 3, 4, IZ_FALSE, IZ_TRUE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT4x1, 4, 1, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT4x2, 4, 2, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT4x3, 4, 3, IZ_FALSE, IZ_TRUE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_FLOAT4x4, 4, 4, IZ_FALSE, IZ_TRUE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT,  1, 1, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT1, 1, 1, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT2, 1, 2, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT3, 1, 3, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT4, 1, 4, IZ_TRUE, IZ_FALSE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT1x1, 1, 1, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT1x2, 1, 2, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT1x3, 1, 3, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT1x4, 1, 4, IZ_TRUE, IZ_FALSE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT2x1, 2, 1, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT2x2, 2, 2, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT2x3, 2, 3, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT2x4, 2, 4, IZ_TRUE, IZ_FALSE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT3x1, 3, 1, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT3x2, 3, 2, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT3x3, 3, 3, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT3x4, 3, 4, IZ_TRUE, IZ_FALSE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT4x1, 4, 1, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT4x2, 4, 2, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT4x3, 4, 3, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_INT4x4, 4, 4, IZ_TRUE, IZ_FALSE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL,  1, 1, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL1, 1, 1, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL2, 1, 2, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL3, 1, 3, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL4, 1, 4, IZ_TRUE, IZ_FALSE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL1x1, 1, 1, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL1x2, 1, 2, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL1x3, 1, 3, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL1x4, 1, 4, IZ_TRUE, IZ_FALSE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL2x1, 2, 1, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL2x2, 2, 2, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL2x3, 2, 3, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL2x4, 2, 4, IZ_TRUE, IZ_FALSE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL3x1, 3, 1, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL3x2, 3, 2, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL3x3, 3, 3, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL3x4, 3, 4, IZ_TRUE, IZ_FALSE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL4x1, 4, 1, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL4x2, 4, 2, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL4x3, 4, 3, IZ_TRUE, IZ_FALSE),
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_BOOL4x4, 4, 4, IZ_TRUE, IZ_FALSE),

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_STRING,  0, 0, IZ_FALSE, IZ_FALSE),		// 文字列
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_TEXTURE, 0, 0, IZ_FALSE, IZ_FALSE),		// テクスチャ

__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_SAMPLER1D, 0, 0, IZ_FALSE, IZ_FALSE),		// 1Dサンプラ
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_SAMPLER2D, 0, 0, IZ_FALSE, IZ_FALSE),		// 2Dサンプラ
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_SAMPLER3D, 0, 0, IZ_FALSE, IZ_FALSE),		// 3Dサンプラ
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_SAMPLERRECT, 0, 0, IZ_FALSE, IZ_FALSE),	// RECTサンプラ
__PE_PARAM_TYPE__(E_POSTEFFECT_PARAMETER_TYPE_SAMPLERCUBE, 0, 0, IZ_FALSE, IZ_FALSE),	// CUBEサンプラ
