#include "graph/ogl/OGLExtFuncProxy.h"

using namespace uranus;

#define UN_OGL_DECL_EXT_PROC(type, name)	type COGLExtFuncProxy::_##name = UN_NULL

UN_OGL_DECL_EXT_PROC(PFNGLFRAMEBUFFERTEXTURE2DPROC, glFramebufferTexture2D);
UN_OGL_DECL_EXT_PROC(PFNGLGENFRAMEBUFFERSPROC, glGenFramebuffers);
UN_OGL_DECL_EXT_PROC(PFNGLBINDFRAMEBUFFERPROC, glBindFramebuffer);
UN_OGL_DECL_EXT_PROC(PFNGLDELETEFRAMEBUFFERSPROC, glDeleteFramebuffers);
UN_OGL_DECL_EXT_PROC(PFNGLGENBUFFERSPROC, glGenBuffers);
UN_OGL_DECL_EXT_PROC(PFNGLBUFFERDATAPROC, glBufferData);
UN_OGL_DECL_EXT_PROC(PFNGLDELETEBUFFERSPROC, glDeleteBuffers);
UN_OGL_DECL_EXT_PROC(PFNGLGETBUFFERSUBDATAPROC, glGetBufferSubData);
UN_OGL_DECL_EXT_PROC(PFNGLBINDBUFFERPROC, glBindBuffer);
UN_OGL_DECL_EXT_PROC(PFNGLGENRENDERBUFFERSPROC, glGenRenderbuffers);
UN_OGL_DECL_EXT_PROC(PFNGLDELETERENDERBUFFERSPROC, glDeleteRenderbuffers);
UN_OGL_DECL_EXT_PROC(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray);
UN_OGL_DECL_EXT_PROC(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer);
