#if !defined(__IZANAGI_SCENEGRAPH_SCENE_DEFS_H__)
#define __IZANAGI_SCENEGRAPH_SCENE_DEFS_H__

namespace izanagi {
	/**
	*/
	enum E_SCENE_REGISTER_TYPE {
		E_SCENE_REGISTER_TYPE_NORMAL = 0,
		E_SCENE_REGISTER_TYPE_OPACITY,
		E_SCENE_REGISTER_TYPE_TRANSLUCENT,

		E_SCENE_REGISTER_TYPE_NUM,
		E_SCENE_REGISTER_TYPE_FORCE_INT32 = 0x7fffffff,
	};

	/**
	*/
	enum E_SCENE_RENDER_SHADER_TYPE {
		E_SCENE_RENDER_SHADER_TYPE_CLASSIFY = 0,
		E_SCENE_RENDER_SHADER_TYPE_Z_SORT,

		E_SCENE_RENDER_SHADER_TYPE_NUM,
		E_SCENE_RENDER_SHADER_TYPE_FORCE_INT32 = 0x7fffffff,
	};
}	// namespace izanagi

#endif	// #if !defined(__IZANAGI_SCENEGRAPH_SCENE_DEFS_H__)
