# Builds all the projects in the solution...
.PHONY: all_projects
all_projects: Graph Io Math Std System DebugUtil Text PostEffect Shader Resource Animation ThreadModel SceneGraph Terra 

# Builds project 'Graph'...
.PHONY: Graph
Graph: 
	make --directory="." --file=Graph.makefile

# Builds project 'Io'...
.PHONY: Io
Io: 
	make --directory="." --file=Io.makefile

# Builds project 'Math'...
.PHONY: Math
Math: 
	make --directory="." --file=Math.makefile

# Builds project 'Std'...
.PHONY: Std
Std: 
	make --directory="." --file=Std.makefile

# Builds project 'System'...
.PHONY: System
System: 
	make --directory="." --file=System.makefile

# Builds project 'DebugUtil'...
.PHONY: DebugUtil
DebugUtil: 
	make --directory="." --file=DebugUtil.makefile

# Builds project 'Text'...
.PHONY: Text
Text: 
	make --directory="." --file=Text.makefile

# Builds project 'PostEffect'...
.PHONY: PostEffect
PostEffect: 
	make --directory="." --file=PostEffect.makefile

# Builds project 'Shader'...
.PHONY: Shader
Shader: 
	make --directory="." --file=Shader.makefile

# Builds project 'Resource'...
.PHONY: Resource
Resource: 
	make --directory="." --file=Resource.makefile

# Builds project 'Animation'...
.PHONY: Animation
Animation: 
	make --directory="." --file=Animation.makefile

# Builds project 'ThreadModel'...
.PHONY: ThreadModel
ThreadModel: 
	make --directory="." --file=ThreadModel.makefile

# Builds project 'SceneGraph'...
.PHONY: SceneGraph
SceneGraph: 
	make --directory="." --file=SceneGraph.makefile

# Builds project 'Terra'...
.PHONY: Terra
Terra: 
	make --directory="." --file=Terra.makefile

# Cleans all projects...
.PHONY: clean
clean:
	make --directory="." --file=Graph.makefile clean
	make --directory="." --file=Io.makefile clean
	make --directory="." --file=Math.makefile clean
	make --directory="." --file=Std.makefile clean
	make --directory="." --file=System.makefile clean
	make --directory="." --file=DebugUtil.makefile clean
	make --directory="." --file=Text.makefile clean
	make --directory="." --file=PostEffect.makefile clean
	make --directory="." --file=Shader.makefile clean
	make --directory="." --file=Resource.makefile clean
	make --directory="." --file=Animation.makefile clean
	make --directory="." --file=ThreadModel.makefile clean
	make --directory="." --file=SceneGraph.makefile clean
	make --directory="." --file=Terra.makefile clean

